services:
    sql: 
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "Your_password123"
        ports:
            - "1433:1433"
        volumes:
        - sql-data:/var/opt/mssql
volumes:
    sql-data:
        